# Generated by Django 3.1.2 on 2020-11-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart',
            new_name='basket',
        ),
        migrations.AddField(
            model_name='basket',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basket',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='customer_orders', to='bboard.Order', verbose_name='Заказы'),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая стоимость заказа'),
        ),
        migrations.AlterField(
            model_name='basketproduct',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Общая стоимость заказа'),
        ),
    ]
