# Generated by Django 3.1.2 on 2020-12-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20201128_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
