# Generated by Django 3.1.2 on 2020-11-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
