# Generated by Django 3.1.2 on 2020-12-09 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_basketproduct_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketproduct',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bboard.customer', verbose_name='Покупатель'),
        ),
    ]
