# Generated by Django 3.1.2 on 2020-11-08 14:07

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20201102_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to=bboard.models.image_directory_path, verbose_name='Фото'),
        ),
    ]
