# Generated by Django 3.1.2 on 2020-11-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='media', verbose_name='Фото'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
